#!/bin/bash
[ -z "$1" ] && echo "Usage: cpprun file.cpp [args...]" && exit 1
file="$1"
shift 1
dir=$(dirname "$file")
base=$(basename "${file%.*}")
out="$dir/$base"
g++ -std=c++17 -Wall -Wextra -Werror -o "$out" "$file" && "$out" "$@"
